import {
  mdiAccountOutline,
  mdiAlertDecagramOutline,
  mdiBriefcaseOutline,
  mdiCardTextOutline,
  mdiCartOutline,
  mdiCash,
  mdiCheckCircleOutline,
  mdiClipboardTextOutline,
  mdiCubeOutline,
  mdiFile,
  mdiGridLarge,
  mdiHomeOutline,
  mdiKey,
  mdiMessageOutline,
} from "@mdi/js"

export type NavigationConfigProps = {
  headMenu?: string
  key: string
  path: string
  pathProps?: any
  title: string
  color?: string
  icon?: string
  breadcrumb?: false
  subMenu: NavigationConfigProps[]
}

const navigationConfig: NavigationConfigProps[] = [
  {
    key: "dashboard",
    path: "",
    title: "Dashboard",
    icon: mdiHomeOutline,
    breadcrumb: false,
    color: "success",
    subMenu: [
      {
        key: "default",
        path: "/dashboard/default",
        title: "Default",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "crypto",
        path: "/dashboard/crypto",
        title: "Crypto",
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    key: "filesManager",
    path: "/apps/files",
    title: "Files",
    color: "danger",
    icon: mdiFile,
    breadcrumb: false,
    subMenu: [],
  },
  {
    key: "invoice",
    path: "/apps/invoice",
    title: "Invoice",
    color: "danger",
    icon: mdiClipboardTextOutline,
    breadcrumb: false,
    subMenu: [],
  },
  {
    key: "chat",
    path: "/apps/chat",
    title: "Chat",
    color: "danger",
    icon: mdiMessageOutline,
    breadcrumb: false,
    subMenu: [],
  },
  {
    key: "todos",
    path: "/apps/todos",
    title: "Todos",
    color: "danger",
    icon: mdiCheckCircleOutline,
    breadcrumb: false,
    subMenu: [],
  },
  {
    key: "commerce",
    path: "",
    title: "e-Commerce",
    icon: mdiCartOutline,
    color: "danger",
    breadcrumb: false,
    subMenu: [
      {
        key: "productList",
        path: "/apps/ecommerce/product-list",
        title: "Product List",
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    key: "layouts",
    path: "",
    headMenu: "UI",
    title: "Layouts",
    icon: mdiGridLarge,
    color: "info",
    breadcrumb: false,
    subMenu: [
      {
        key: "grid",
        path: "/layouts/grid",
        title: "Grid",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "flexrow",
        path: "/layouts/flexrow",
        title: "Flex Row",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "flexcolumn",
        path: "/layouts/flexcolumn",
        title: "Flex Column",
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    key: "Card",
    path: "",
    title: "Card",
    icon: mdiCardTextOutline,
    color: "info",
    breadcrumb: false,
    subMenu: [
      {
        key: "statistics",
        path: "/card/statistics",
        title: "Statistics",
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    key: "Colors",
    path: "/colors",
    title: "Colors",
    icon: mdiCartOutline,
    color: "info",
    breadcrumb: false,
    subMenu: [],
  },
  {
    key: "Components",
    path: "",
    title: "Components",
    icon: mdiBriefcaseOutline,
    color: "info",
    breadcrumb: false,
    subMenu: [
      {
        key: "avatar",
        path: "/components/avatar",
        title: "Avatar",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "button",
        path: "/components/button",
        title: "Button",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "chip",
        path: "/components/chip",
        title: "Chip",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "collapse",
        path: "/components/collapse",
        title: "Collapse",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "datalist",
        path: "/components/datalist",
        title: "Datalist",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "dropdown",
        path: "/components/dropdown",
        title: "Dropdown",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "list",
        path: "/components/list",
        title: "List",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "loader",
        path: "/components/loader",
        title: "Loader",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "modal",
        path: "/components/modal",
        title: "modal",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "navbar",
        path: "/components/navbar",
        title: "Navbar",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "pagination",
        path: "/components/pagination",
        title: "Pagination",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "tab",
        path: "/components/tab",
        title: "Tab",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "tooltip",
        path: "/components/tooltip",
        title: "Tooltip",
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    key: "formelements",
    path: "",
    title: "Form Elements",
    icon: mdiCubeOutline,
    color: "info",
    breadcrumb: false,
    subMenu: [
      {
        key: "checkbox",
        path: "/formelement/checkbox",
        title: "Checkbox",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "input",
        path: "/formelement/input",
        title: "Input",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "select",
        path: "/formelement/select",
        title: "Select",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "switch",
        path: "/formelement/switch",
        title: "Switch",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "textarea",
        path: "/formelement/textarea",
        title: "Textarea",
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    headMenu: "Pages",
    key: "user",
    path: "",
    title: "User",
    icon: mdiAccountOutline,
    color: "warning",
    breadcrumb: false,
    subMenu: [
      {
        key: "profile",
        path: "/user/profile",
        title: "Profile",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "view",
        path: "/user/view",
        title: "View",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "edit",
        path: "/user/edit",
        title: "Edit",
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    key: "authentication",
    path: "",
    title: "Authentication",
    icon: mdiKey,
    color: "warning",
    breadcrumb: false,
    subMenu: [
      {
        key: "login",
        path: "/pages/login",
        pathProps: { target: "_blank", rel: "noreferrer noopener" },
        title: "Login",
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "sociallogin",
        path: "/pages/sociallogin",
        title: "Social Login",
        pathProps: { target: "_blank", rel: "noreferrer noopener" },
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "register",
        path: "/pages/register",
        pathProps: { target: "_blank", rel: "noreferrer noopener" },
        title: "Register",
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    key: "error",
    path: "",
    title: "Error",
    icon: mdiAlertDecagramOutline,
    color: "warning",
    breadcrumb: false,
    subMenu: [
      {
        key: "notfound",
        path: "/pages/notfound",
        title: "404",
        pathProps: { target: "_blank", rel: "noreferrer noopener" },
        breadcrumb: false,
        subMenu: [],
      },
      {
        key: "comingsoon",
        path: "/pages/comingsoon",
        title: "500",
        pathProps: { target: "_blank", rel: "noreferrer noopener" },
        breadcrumb: false,
        subMenu: [],
      },
    ],
  },
  {
    key: "pricing",
    path: "/page/pricing",
    title: "Pricing",
    icon: mdiCash,
    color: "warning",
    breadcrumb: false,
    subMenu: [],
  },
  {
    headMenu: "Others",
    key: "documentation",
    path: "/documentation",
    title: "Documentation",
    icon: mdiAlertDecagramOutline,
    color: "warning",
    breadcrumb: false,
    subMenu: [],
  },
]

export default navigationConfig
