[build]
  publish = "packages/demo/build"
  command = "yarn run build"
  functions = "functions"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
